return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  event = { "BufReadPre", "BufNewFile" },
  main = "nvim-treesitter.configs",
  opts = {
    highlight = { enable = true },
    indent = { enable = true },
    auto_install = true,
    ensure_installed = {
      "lua",
      "vim",
      "vimdoc",
      "go",
      "nix",
      "json",
      "yaml",
      "typescript",
      "javascript",
      "tsx",
      "html",
      "css",
      "markdown",
      "markdown_inline",
      "bash",
    },
  },
}
